#! /bin/sh

## Tell xrandr how to set up my monitors
xrandr --output DisplayPort-0 --primary --rate 60.00 --mode 1920x1080 --right-of HDMI-A-0 --output HDMI-A-0 --rate 60.00 --mode 1920x1080

################
## Autostarts ##
################

sxhkd &
picom &
dunst -config $HOME/.config/dunst/dunstrc &
nitrogen --restore &

~/.config/polybar/launch.sh &

###########################
## Workspace and windows ##
###########################

bspc monitor DisplayPort-0 -d 6 7 8 9 10
bspc monitor HDMI-A-0 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

########################
## Bspwm Window Rules ##
########################

## Nothing yet

#############
## Theming ##
#############

## Dracula theme

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
